---
title: "fitness5"
author: "Alice Danguy des Déserts"
date: "18 mars 2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, echo=FALSE}




Sys.time()
cat("\n\nfitness5.R\n\n")
rm(list = ls())
graphics.off()
set.seed(1)

suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(compiler))
suppressPackageStartupMessages(library(ggpubr))


titre_mod1 <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag1.csv"
titre_mod2 <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag2.csv"
titre_mod3 <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag3.csv"
titre_mod4 <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag4.csv"

titre_mod5 <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag5.csv"


titre_mod5bis <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag6.csv"
titre_mod5ter <-"/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag7.csv"
titre_mod5quater <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/res10k/RES_10k/resag8.csv"


titre_crosses <- "/home/adanguydesd/Documents/These_Alice/croisements/temp/pour_NDurand/crosses_10k.txt"
c <- fread(titre_crosses)

m1 <- fread(titre_mod1, skip=5) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))

m2 <- fread(titre_mod2, skip=5) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))

m3 <- fread(titre_mod3, skip=5) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))

m4 <- fread(titre_mod4, skip=5) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))

m5 <- fread(titre_mod5, skip=5) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))



m5bis <- fread(titre_mod5bis, skip=6) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))



m5ter <- fread(titre_mod5ter, skip=7) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))

m5quater <- fread(titre_mod5quater, skip=8) %>% dplyr::select(-generation)%>% inner_join(c, by=c("P1","P2")) %>%
  arrange(desc(uc)) %>% as.data.frame() %>%
  mutate(choosen=ifelse(nbprogeny >30, "nbprogeny > 30", "nbprogeny < 30")) %>%
  mutate(choosen=factor(choosen, levels=c("nbprogeny > 30", "nbprogeny < 30")))



g1 <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m1, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 1")+
  theme(plot.title = element_text(hjust = 0.5))



g2 <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m2, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 2")+
  theme(plot.title = element_text(hjust = 0.5))





g3 <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m3, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 3")+
  theme(plot.title = element_text(hjust = 0.5))





g4 <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m4, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 4")+
  theme(plot.title = element_text(hjust = 0.5))







g5 <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m5, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 5")+
  theme(plot.title = element_text(hjust = 0.5))



g5bis <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m5bis, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 5 [UCij * qij * Dij if qij*Dij >= 1 else UCij * 0.1 ] ")+
  theme(plot.title = element_text(hjust = 0.5))

g5ter <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m5ter, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 5 [UCij * (max qij 0.001)  *  Dij]")+
  theme(plot.title = element_text(hjust = 0.5))

g5quater <- c %>% ggplot(aes(x=gebv, y=sd)) + geom_point()+
  geom_point(data=m5quater, aes(x=gebv, y=sd, col=choosen), size=3) +
  theme_light() + ggtitle("mod 5 [UCij * qij * Dij  if qij*Dij>=1  else UCij * 0. 01  *  Dij]")+
  theme(plot.title = element_text(hjust = 0.5))


# total=sum(m5$nbprogeny)
# qsel=0.07
# 
# s=0.1
# data <- data.frame()
# for (s in seq(min(m5$gebv)-4, max(m5$gebv)+4, 0.001)) {
#   
#   contrainte <-  m5 %>% rowwise() %>%
#     mutate(q=pnorm(s, mean=gebv, sd=sd, lower.tail = F)) %>%
#     mutate(qd=nbprogeny*q) %>%
#     ungroup() %>%
#     summarise(r=sum(qd) - qsel*total) %>%
#     unlist() %>%
#     as.vector()
#   
#   
#   data <- rbind(data, data.frame(s=s, contrainte=contrainte))
#   
#   
#   
# }


# data2 <- data %>% mutate(contrainte=abs(contrainte)) %>% arrange(contrainte)
# head(data2)
# 
# 
# s <- data2$s[1]

```




```{r, echo=T}


ggarrange(g1, g2, g3, g4, g5,g5bis, g5ter, g5quater, common.legend = T, ncol=1, nrow=1)


# res <- m5 %>%
#   rowwise() %>%
#   mutate(q=pnorm(s, mean=gebv, sd=sd, lower.tail = F)) %>%
#   dplyr::select(P1, P2, gebv, sd, uc, q, nbprogeny) %>%
#   mutate(qXnbprogeny=q*nbprogeny) %>%
#   mutate(ucXqXnbprogeny=uc*q*nbprogeny) %>%
#   ungroup() %>%
#   arrange(desc(qXnbprogeny)) %>%
#   as.data.frame() %>%
#   mutate(proportion_fitness=cumsum(ucXqXnbprogeny)/(qsel*total)) %>%
#   mutate(proportion_fitness=proportion_fitness/max(proportion_fitness)) %>%
#   mutate(proportion_dij_opti=cumsum(qXnbprogeny)/(qsel*total))
# 
# head(res, 10)
# 
# tail(res, 10)
  

```

